name: Rename Go Module and Create ZIP

# This workflow can be triggered manually from the "Actions" tab in GitHub.
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      # 步骤 1: 检出代码
      - name: Checkout repository
        uses: actions/checkout@v4
      
      # 步骤 2: 批量替换所有 .go 文件中的模块路径
      - name: Find and replace module paths in .go files
        # 使用 find 结合 xargs 和 sed 来高效地批量替换
        run: |
          find . -type f -name "*.go" -print0 | xargs -0 sed -i 's|github.com/labulakalia/water|github.com/XLESSGo/water|g'

      # 步骤 3: 更新 go.mod 文件中的模块名
      - name: Update go.mod
        run: |
          # 确保安装了 Go 语言环境
          sudo apt-get update && sudo apt-get install golang-go
          # 使用 go mod edit 命令更新模块名
          go mod edit -module github.com/XLESSGo/water
          
     # Step 4: Configure Git user for commit
      - name: Configure Git User
        run: |
          git config user.name "DarienRaymond"
          git config user.email "admin@v2ray.com"

      # Step 5: Commit the changes
      - name: Commit changes
        run: |
          git add .
          git commit -m "Rename Go Module: v4ray to v2ray"

      # Step 6: Push the changes back to the repository
      - name: Push changes
        run: |
          git push
